version: 2.1

workflows:
  build-and-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - run:
          name: Configuration
          command: |
            npm config set loglevel warn
            npm config set scripts-prepend-node-path auto
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "export CI_BRANCH=${CIRCLE_BRANCH}" >> $BASH_ENV
            echo "export CI_BUILD_NUMBER=${CIRCLE_BUILD_NUM}" >> $BASH_ENV
            echo "export CI_COMMIT=${CIRCLE_SHA1}" >> $BASH_ENV
            echo "export CI_COMMIT_SHORT=${CIRCLE_SHA1:0:8}" >> $BASH_ENV
            echo "export CI_TAG=${CIRCLE_TAG}" >> $BASH_ENV
      - run:
          name: Check version
          command: |
            git --version
            node --version
            npm --version
            yarn --version
      - run:
          name: Install packages
          command: |
            yarn
      - run:
          name: Build
          command: |
            yarn clean
            yarn test
            yarn build
